### ISSUE TITLE
issue releasing to pypi

### ISSUE THREAD

**Issue by barneydobson** [ImperialCollegeLondon/wsi#127]
https://github.com/ImperialCollegeLondon/wsi/actions/runs/11932607759/job/33258089433

seems to work on the test deployment but not on actual publish... any ideas @dalonsoa ?

**Comment by dalonsoa** [comment]
Contrary to `SWMManywhere`, that uses `hatchling` to build the package, `WSIMOD` uses the good old `setuptools`. That means that creating a release with the corresponding tag does not automatically update the version number. The one set for WSIMOD is still 0.4.0, as [indicated in `pyproject.toml`](https://github.com/ImperialCollegeLondon/wsi/blob/a802a55625c9d8c431ec819820f59f4e09effc37/pyproject.toml#L12), which already exist in PyPI, regadless of the what they resease says and how many tags you create.

The options are:
- Manually change the version number to 0.5.0 in `pyproject.toml`
- Adopt `hatchling`, like SWMManywhere

**Comment by barneydobson** [comment]
I have found `hatchling` easier with SWMManywhere - but will that get confused since we have a variety of releases that do not follow `0.X.X` convention? I remember that being an issues with SWMManywhere

**Comment by dalonsoa** [comment]
Not sure, to be honest. I've as much experience with hatchling as you do. I don't thin it should be a problem, but cannot say for sure. Maybe ask Taher.
