### ISSUE TITLE
Deployment in PyPI with new releases

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/wsi#23]
The current instructions explain how to install WSIMOD using `conda` directly from the GitHub repo. There's nothing wrong with that, but it will be more convenient to deploy the tool to a common repository, like PyPI, allowing the installation of WSIMOD in exactly the same way but also enforcing a versioning, which is necessary for a professional tool. 

I'd suggest a something similar to what we[ implemented in MUSE](https://github.com/SGIModel/MUSE_OS/blob/c66ef1019925f548087d3fd76549ca0b1b9f993b/.github/workflows/ci.yml#L88) but triggered by releases,[ as it is done in Health-GPS](https://github.com/imperialCHEPI/healthgps/blob/735e0f3e0ea1f365b648181f281eee704c4a86bb/.github/workflows/ci.yml#L152). 

Documentation needs updating accordingly.

## Update 

As much as we would like to to this soon, there are several issues that need solving before we are confident we are deploying a robust tool with a clear documentation (including well documented API documentation):

- [x] #30 
- [x] #31 
- [ ] #33 
- [ ] #34 
- [ ] #35

**Comment by dalonsoa** [comment]
@barneydobson , this is not urgent - in the sense that it does not affect other work that we need to do - but I think it will be useful to have it done as soon as possible and release a new version of the software, deployed in PyPI, so any future development follows the same pattern. 

Are you happy for us to create a new release (0.4.0, if we continue from the last one) and move on from there?

**Comment by barneydobson** [comment]
@dalonsoa  yep absolutely!

**Comment by dalonsoa** [comment]
@barneydobson , it seems this will take a while. We feel the tool needs a bit more work before we can deploy it with confidence in `pypi`. See updated description.

@liuly12 , this should not affect the DAFNI side of the project.
