### ISSUE TITLE
Enable overrides

### ISSUE THREAD

**Issue by barneydobson** [ImperialCollegeLondon/wsi#72]
An issue to keep track of all the different things that (may) need `apply_overrides` behaviour defined for (linked with #66 and #54)
- [x] `Node`
- [x] `WTW/WWTW`
- [ ] `FWTW` [Under review]
- [ ] `Land` #71 [Under reivew]
- [ ] `NutrientPool` #71 [Under reivew]
- [ ] `Catchment` [No additional parameters to be updated]
- [ ] `Demand` (and subclasses) [Under review]
- [ ] `Distribution` (and subclasses) [Under review]
- [ ] `Sewer` [Under review]
- [ ] `Storage` (and subclasses) [Wait to be merged]
- [x] `Waste` - not necessary

**Comment by liuly12** [comment]
@barneydobson Should overrides be added to `Tank` and its superclasses (e.g., `ResidenceTank`, `DecayTank`, etc.) as well?

**Comment by barneydobson** [comment]
I'm not sure it's necessary as you don't substantiate a `Tank` from a `config` file. All `Tanks` are specific to their node class

**Comment by barneydobson** [comment]
think these are all done now
