### ISSUE TITLE
`data_input_dict` overrides

### ISSUE THREAD

**Issue by barneydobson** [ImperialCollegeLondon/wsi#74]
Discussed in #71 with @liuly12  . I think there is a good case to be made for allowing this - as it seems like people would probably want to quickly switch between data forcing.

Probably this should receive a `str` for the file path, and then load and format the data as in `model.load`. Which means that the functionality the loads/formats should be its own function - I guess under the `Node` object?

**Comment by liuly12** [comment]
So I'm thinking this in a scenario of global sensitivity analysis, which might be highly likely to be used in the forseeable future. In the SAFE tool box, it generates an array where each column represents a scenario of changed data forcing. But if we want to enable data forcing change for WSIMOD, we need to save to the csv first and change the `str` of the file path. I wonder do we want to develop any non-saving ways for a batch change of data forcing in sensitivity test?

**Comment by barneydobson** [comment]
As in the forcing data is generated on the fly during SA?

**Comment by liuly12** [comment]
yep - basically replace the data_input_dict directly rather than through a file path

**Comment by barneydobson** [comment]
Sorry I mean (for clarification) - does SAFE generate forcing data on the fly - and that is the kind of behaviour we want to enable?

**Comment by liuly12** [comment]
They do as far as I understand

**Comment by barneydobson** [comment]
Cool - OK I guess could we update `load` to check whether is a `str` or `dict`?

**Comment by liuly12** [comment]
or update `node`? I plan to try different options this morning and see what you think when I'm ready. Does this sound a good plan?

**Comment by barneydobson** [comment]
Ohh I see yes since the overrides would be applied in `node` - but yes it would be check the data type there.

I think that makes sense
